#!/usr/bin/env python3
"""
Emit js/commonsImageUrls.js from scripts/commons_images.py (single source of truth).

Run after editing COMMONS_IMAGES in commons_images.py:
  python3 scripts/emit_commons_image_urls_js.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))
from commons_images import COMMONS_IMAGES  # noqa: E402


def main() -> int:
    out = ROOT / "js" / "commonsImageUrls.js"
    lines = [
        "// AUTO-GENERATED by scripts/emit_commons_image_urls_js.py — do not edit.",
        "// Same URLs as scripts/commons_images.py. Used when a local images/ file is missing.",
        "window.COMMONS_IMAGE_URLS = {",
    ]
    for rel, url in COMMONS_IMAGES:
        key = f"images/{rel}"
        lines.append(f"  {json.dumps(key)}: {json.dumps(url)},")
    lines.append("};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
